name: finans_takip_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0' # SDK versiyonunu güncelledim

dependencies:
  flutter:
    sdk: flutter
  
  # State Management için
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  
  # Lokal Veritabanı için
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3

  # UYGULAMA İÇİN GEREKLİ PAKETLER BURADA OLMALI
  fl_chart: ^0.68.0 
  intl: ^0.19.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Veritabanı model kodlarını otomatik oluşturmak için
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.9
  flutter_lints: ^4.0.0 # Lints paketini güncelledim

flutter:
  uses-material-design: true